### ISSUE TITLE
Team Review: Data Vizionaries

### ISSUE THREAD

**Issue by hlarya-uoa** [INFO-526-FA24/project-2-epidata#1]
1. Full names and githubnames of reviewing team
Team: Data Vizionaries
Members: Himanshu Lal, Kapil Parab, Abhay Nandiraju: srikrish2812, Maksim Kulik: h-akston
2. Describe the goal of the project.
This project aims to explore and compare major pandemics in history, including Cholera, Dengue, and COVID-19, using features like infection spread, mortality rates, seasonal patterns, and economic impact to uncover key similarities and differences between these diseases across different time periods.

3. Describe the data used or collected.
This project uses three key datasets from the WHO to analyze major disease outbreaks:
	1. COVID-19 Dataset: Tracks daily reported cases and deaths worldwide from January 2020 to September 2024, offering a detailed view of the pandemic’s spread by country.
	2. Cholera Dataset: Provides annual data from 2000 to 2023 on cholera cases, deaths, and incidence rates by country, highlighting trends over time.
	3. Dengue Fever Dataset: Contains monthly case data from 2010 to 2024, focusing on severe cases, deaths, and fatality rates by country and region.

The team has given a brief description of dataset with the links but a summary of data model ( columns, rows, types of data). Please include  a summary of the data to help view get an insight on how the data is represented for each pandemic and how it relates with the question to be answered.

4. Describe how the research question will be answered, e.g. what approaches / methods will be used.

	• Q1: Stream graphs to show the progression of infection and death counts over time for each pandemic.
	• Q2: An interactive Shiny app to display a global heatmap
	• Q3: Time series graphs and scatter plots to analyse changes in disease growth rates before and after media coverage
	• Q4: Radar charts to compare key factors like incubation period, mortality rate, and illness duration across the three pandemics.

Which variable are to be used is missing in the approach plan. With no description of columns, the mapping from dataset to question is difficult. 

5. Is there anything that is unclear from the proposal?
A short Description of the type of dataset. What type of data, it includes and how those variables will relate to the question problem.
6. Provide constructive feedback on how the team might be
able to improve their project.
Everything is well defined. The questions are well formed and the selected visualization will provide valuable insights to the viewers. Please include the description of dataset model including column description. This will help to understand the dataset better and relate to the problems.
7. What aspect of this project are you most interested in and
would like to see highlighted in the presentation.
Time series graphs for analysing the changes in growth patterns and the shiny interactive app for heatmaps.
8. Provide constructive feedback on any issues with file and/or
code organization.
The QMD file is properly defined and well formatted. 
9. (Optional) Any further comments or feedback?
Excited to see the visualizations.

**Comment by YitianQian777** [comment]
Revised proposal based on this peer review feedback.
