### ISSUE TITLE
Review from team Data Nexus

### ISSUE THREAD

**Issue by SiddheshwarSinghNegi** [INFO-526-FA24/project-2-epidata#10]
Strengths: The project stands out with its use of unique and diverse chart types, which provide a fresh perspective on the data. The thoughtful comparison between various diseases is both insightful and engaging, offering a comprehensive understanding of the topic. Additionally, the presentation of unique insights showcases a deep dive into the subject matter and adds significant value to the overall analysis.

Weaknesses: The project contains an overwhelming amount of text, which can make it challenging for the audience to stay focused and absorb key points. Some visualizations could benefit from being zoomed in or enlarged to improve readability and ensure that important details are not overlooked. Furthermore, there is a lack of emphasis on critical data points, which might cause the most impactful information to get lost in the overall content.

**Comment by YitianQian777** [comment]
Thank you for the feedbacks.
