### ISSUE TITLE
Peer Review of iShowcase Poster by Insight Decoders

### ISSUE THREAD

**Issue by Hemanath17ua** [INFO-526-FA24/project-2-epidata#12]
Hello Team Epidata,

Strength: 
A radar plot, also known as a spider or web chart, is an effective visualization tool for comparing multiple variables across different categories. It provides a clear, holistic view by plotting data points radiating from a central axis, connecting them into a polygon. This enhances presentations by making patterns, strengths, and weaknesses easily identifiable at a glance.

Weakness: 
The poster contains excessive text; explanations should be concise, with smaller, focused visualizations to improve clarity.

**Comment by YitianQian777** [comment]
Thank you for the feedbacks.
