### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by Saharsh-Bhave** [INFO-526-FA24/project-2-epidata#2]
1. Full names and githubnames of reviewing team

| **Full Names**          | **GitHub Names**    |
|------------------------|------------------------|
| Saharsh Bhave         | Saharsh-Bhave         |
| LIBIN N George        | libin-n-g             |
| Ajeet Singh           | iam-ajeetsingh        |
| Navyashree Madhu      | NavyasreeMadhu14      |

2. Describe the goal of the project.  
The project aims to explore significant pandemics like Cholera, Dengue, and COVID-19 through data visualizations, focusing on infection spread rates, mortality, seasonal patterns, economic impacts, and the timeline from initial reports to large-scale outbreaks.

3. Describe the data used or collected.  
The project utilizes datasets from the World Health Organization (WHO) focusing on three major disease outbreaks: COVID-19, Cholera, and Dengue Fever. Here's a detailed description of each dataset:

- The [COVID-19 dataset](https://data.who.int/dashboards/covid19/data) provides daily reported cases and deaths at the country level from January 4, 2020, to September 22, 2024, offering a detailed timeline of the pandemic’s progression across regions.
- The [Cholera dataset](https://worldhealthorg.shinyapps.io/page10cholera_data/) includes annual country-level data on cases, mortality, and incidence rates from 2000 to 2023, with key columns such as Country, Region, Year, Total Cases, Deaths, and Case Fatality Rate (CFR).
- The [Dengue Fever dataset](https://worldhealthorg.shinyapps.io/dengue_global/) contains monthly case data by country from January 1, 2010, to September 1, 2024, capturing metrics on severe cases, deaths, and fatality rates, and providing information across multiple dimensions, including date, region, country, and case severity.

- WHO-sourced datasets, though generally reliable, face limitations like under-reporting in regions with limited healthcare and inconsistencies in case definitions across countries. Varying temporal resolutions (annual, monthly, daily) necessitate harmonization for consistent analysis. For this they are handling missing data and rename columns in all three datasets to follow a consistent format. They will modify the values of time columns to be in the year-month-date format and will segment the time periods as required.

4. Describe how the research question will be answered, e.g. what approaches / methods will be used.  
- For the first research question, this team will use a stream graph to plot infected counts and death counts with time. The infected counts will be the upper part and the death counts will be the lower part, with x-axis being the timeline. This will allow them to see how fatal a disease was at that time.  
- For the second question, they will use R to create a Shiny app to implement a sliding bar to slide through the time period affected by this pandemic, with each specific time corresponding to a heatmap that depicts the infected areas in the world map. This will allow them to visualize the geographical spread of the pandemic.  
- For the third question, they will use time series to see the disease growth rate and use a scatter plot to understand the changes in disease growth rate before and after news reports. This step will only apply to those pandemics in modern days when there were recorded news media.  
- For the last question, they will use a radar chart for each pandemic to present the pandemic variables, such as incubation period, mortality rate, and illness duration, etc. This will tell about the different conditions during different pandemics.

5. Is there anything that is unclear from the proposal?  
The dimensions of their datasets are not provided, leading to lesser clarity about the data. Number of rows, columns, data-types could have been provided for a clearer glimpse of the dataset.

6. Provide constructive feedback on how the team might be able to improve their project.  
For research question 3, if this team can search archives for the news about the older pandemics and include that in their project, they can get even better visualizations.

7. What aspect of this project are you most interested in and would like to see highlighted in the presentation.  
The entire proposal workflow is interesting. We look forward to understanding whether news reports have any impact on the disease growth rates and highlight the geographical spread and containment of each pandemic. Another topic we are interested in is the pattern by which epidemics hit civilization. Can we predict when it is most likely to have the next epidemic?

8. Provide constructive feedback on any issues with file and/or code organization.  
We suggest that along with the link provided to refer the dataset, while organizing the file include dataset summary explaining the data types and total rows and columns.

10. (Optional) Any further comments or feedback?  
Overall looks good. You could use an R project instead of a single QMD file. This will make the project easier to reproduce.

**Comment by YitianQian777** [comment]
Revised proposal based on this peer review feedback.
