### ISSUE TITLE
Instructor Review 

### ISSUE THREAD

**Issue by annahoju** [INFO-526-FA24/project-2-epidata#3]
Hello team epidata

Overall, your proposal indicates that you are set up for a success. You have a data set that will be able to answer the research questions through the proposed analysis and visualizations. Such an interesting area to study given our recent history with COVID pandemic. 

One area of consideration that I do not see is addressed int he proposal is the approach to the poster presentation. As a team, spend some time storyboarding the poster and consider how such an ambitious project will be translated into a poster.

|          | Available | Earned |
|----------|-----------|--------|
| Data     | 3         |      3  |
| Proposal | 5         |    5    |
| Workflow | 1         |    1    |
| Teamwork | 1         |     1   |
| Total    | 10        |   10     |

**Comment by YitianQian777** [comment]
We added the section of poster ideas into the proposal based on your feedbacks.
