### ISSUE TITLE
Team DataVizionaries review - MOCK iShowcase

### ISSUE THREAD

**Issue by h-akston** [INFO-526-FA24/project-2-epidata#5]
The main strength is the thoroughness and depth of the work - the team has done a lot to make really complex data on 3 different diseases accessible and visually appealing.

The main weakness, which the team is aware of, is cosmetic. Some plots are too small, even for a large-format poster. There is also a lot of text, and when the plots are resized to more optimal size, that text will need to be edited.

Great work overall, we were impressed!

**Comment by YitianQian777** [comment]
Thank you for the feedbacks.
