### ISSUE TITLE
Poster Review By Insight Spark

### ISSUE THREAD

**Issue by Sharanpazhanivel** [INFO-526-FA24/project-2-epidata#7]
Strengths:
- Included a radar chart, which is a unique type of visualization and highly useful for interpreting trends across various scenarios such as COVID-19, Cholera, etc.
- Used R scripts to create the poster, which is impressive and demonstrates significant effort and dedication. Great work!

 Weaknesses:
- Contains more textual information than visualizations, which might prevent the audience from getting a quick overview of the dataset.

**Comment by YitianQian777** [comment]
Thank you for the feedbacks.
