### ISSUE TITLE
Peer Review of iShowcase Poster by Team DataWaves 

### ISSUE THREAD

**Issue by iam-ajeetsingh** [INFO-526-FA24/project-2-epidata#8]
Hello Team epidata,

You have presented the complex data related to different diseases in an accessible and visually engaging manner.
I have following Observations : 

**Strengths:**
1.You have successfully transformed the intricate datasets into interesting visualizations. 
2. You work made the research topic easier to understand.

**Suggestions for Improvement:**
1.The poster contains a considerable amount of text. Simplifying the content and using bullet points could enhance readability and make key information stand out.
2.Enlarging the visualizations would draw more attention to them and aid in data interpretation.

Overall Great Work.

**Comment by YitianQian777** [comment]
Thank you for the feedbacks.
