### ISSUE TITLE
Poster review by Visual voyagers

### ISSUE THREAD

**Issue by gr98765** [INFO-526-FA24/project-2-epidata#9]
Hello team Epidata,

Strength: The project showcases creative and unique visualizations that effectively analyze pandemic data, including the use of a stream graph to reveal valuable trends.

Weakness:The poster has more text compared to visual data; balancing them by simplifying text and enlarging visualizations would enhance clarity and impact.

**Comment by YitianQian777** [comment]
Thank you for the feedbacks.
